#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

# Everything this wizard captures lives in backend/cloudflare-worker/.env —
# gitignored, never committed, never printed back to this terminal in full.
mkdir -p backend/cloudflare-worker
ENV_FILE="backend/cloudflare-worker/.env"
if ! grep -qxF "backend/cloudflare-worker/.env" .gitignore 2>/dev/null; then
  printf '\nbackend/cloudflare-worker/.env\n' >> .gitignore
fi

banner "Cloudflare setup for the KU-KIT Assistant backend"
note "This sets up the Cloudflare account, CLI login, and API token needed"
note "before Claude Code can provision R2 / AI Search / the Worker."
note "Nothing here costs money on Cloudflare's free tier at this project's scale."

# ── Stage 1: account signup ────────────────────────────────────────────────
stage "Cloudflare account"
say "If you already have a Cloudflare account, skip straight past this one."
open_url "https://dash.cloudflare.com/sign-up"
step "Sign up with your email + a password."
step "Check your inbox and click the verification link Cloudflare sends you."
step "Log in at https://dash.cloudflare.com once verified."
pause "Once you're logged into the Cloudflare dashboard, press Enter to continue."

# ── Stage 2: enable Workers & Pages / Workers AI ───────────────────────────
stage "Enable Workers & Pages"
say "This activates the free Workers plan on your account (needed for the"
say "Worker, Workers AI, R2, and AI Search we'll create later)."
open_url "https://dash.cloudflare.com/?to=/:account/workers-and-pages"
step "If prompted, click through to enable Workers & Pages / pick the Free plan."
step "You don't need to create anything here yet — just land on this page once."
pause "Once the Workers & Pages dashboard loads without an activation prompt, press Enter."

# ── Stage 3: wrangler login ─────────────────────────────────────────────────
stage "Log the command line in (wrangler)"
say "This opens a browser tab asking you to authorize the Cloudflare CLI."
say "Approve it there — this wizard will wait."
pause "Press Enter to launch the login flow now."
if npx wrangler login; then
  printf '  %s✓ wrangler login succeeded%s\n' "$GREEN" "$RESET"
else
  warn "wrangler login didn't finish cleanly — re-run this stage later with:"
  note "  npx wrangler login"
fi
say "Verifying..."
WHOAMI_OUT="$(npx wrangler whoami 2>&1 || true)"
printf '%s\n' "$WHOAMI_OUT"
CF_ACCOUNT_ID="$(printf '%s' "$WHOAMI_OUT" | grep -oE '[0-9a-f]{32}' | head -n1 || true)"
if [[ -n "$CF_ACCOUNT_ID" ]]; then
  say "Found your Account ID automatically: $CF_ACCOUNT_ID"
else
  warn "couldn't auto-detect the Account ID from that output — you'll paste it in Stage 5."
fi

# ── Stage 4: API token ──────────────────────────────────────────────────────
stage "Create an API token"
say "The Worker needs a token to call AI Search / Workers AI / R2 / KV on your"
say "behalf. Create a scoped Custom Token — do NOT use your Global API Key."
open_url "https://dash.cloudflare.com/profile/api-tokens"
step "Click 'Create Token'."
step "Click 'Create Custom Token' (the option at the bottom, not a template)."
step "Name it something like 'kukit-assistant-backend'."
step "Under Permissions, add these five rows (Account scope, each set to Edit):"
note "    Account → AI Search → Edit"
note "    Account → Workers AI → Edit"
note "    Account → Workers R2 Storage → Edit"
note "    Account → Workers KV Storage → Edit"
note "    Account → Workers Scripts → Edit"
step "Under Account Resources, select the one account you just set up."
step "Click 'Continue to summary', then 'Create Token'."
step "Copy the token shown ONCE on the next screen (you can't view it again)."
warn "Paste it somewhere like a password manager as a backup — Cloudflare won't show it again."
ask_secret CF_API_TOKEN "Paste the token here (input is hidden):"

if [[ -n "${CF_API_TOKEN:-}" ]]; then
  say "Validating the token against the Cloudflare API..."
  VERIFY_STATUS="$(curl -s -o /tmp/cf-token-verify.$$ -w '%{http_code}' \
    -H "Authorization: Bearer ${CF_API_TOKEN}" \
    -H "Content-Type: application/json" \
    "https://api.cloudflare.com/client/v4/user/tokens/verify" || true)"
  if [[ "$VERIFY_STATUS" == "200" ]]; then
    printf '  %s✓ token is valid%s\n' "$GREEN" "$RESET"
    write_env CF_API_TOKEN "$CF_API_TOKEN"
  else
    warn "token verification returned HTTP $VERIFY_STATUS — double-check the token/permissions."
    warn "saving it anyway so you don't have to retype it; re-run this stage to fix it."
    write_env CF_API_TOKEN "$CF_API_TOKEN"
  fi
  rm -f /tmp/cf-token-verify.$$
else
  warn "no token entered — re-run this wizard to add it before Claude Code can continue."
fi

# ── Stage 5: account ID ─────────────────────────────────────────────────────
stage "Confirm your Account ID"
if [[ -n "${CF_ACCOUNT_ID:-}" ]]; then
  say "Auto-detected earlier: $CF_ACCOUNT_ID"
  if confirm "Does that look right? (visible on the right sidebar of any dashboard page)"; then
    write_env CF_ACCOUNT_ID "$CF_ACCOUNT_ID"
  else
    open_url "https://dash.cloudflare.com/"
    step "Look at the right sidebar of any page in the dashboard — 'Account ID'."
    ask CF_ACCOUNT_ID "Paste your Account ID:"
    write_env CF_ACCOUNT_ID "$CF_ACCOUNT_ID"
  fi
else
  open_url "https://dash.cloudflare.com/"
  step "Look at the right sidebar of any page in the dashboard — 'Account ID'."
  ask CF_ACCOUNT_ID "Paste your Account ID:"
  write_env CF_ACCOUNT_ID "$CF_ACCOUNT_ID"
fi

# ── Stage 6: handoff ────────────────────────────────────────────────────────
stage "Done — hand back to Claude Code"
say "Everything captured is sitting in backend/cloudflare-worker/.env (gitignored,"
say "never committed). You don't need to paste the token or account ID into chat —"
say "just go back and tell Claude you've finished this wizard; it'll read the file"
say "from here and continue provisioning R2 / KV / AI Search / the Worker."

finish
